### ISSUE TITLE
add fatalities

### ISSUE THREAD

**Issue by helioshk** [daenuprobst/covid19-cases-switzerland#19]
Due to the lack of test capacity, the case numbers are of limited value.
The number of fatalities would be a better representation of the extent of the pandemic.
Thanks.

**Comment by zdavatz** [comment]
@helioshk Please start collecting them in your own repository! You can start here: 

https://de.wikipedia.org/wiki/COVID-19-Pandemie_in_der_Schweiz#Todesf%C3%A4lle

please structure your file well and upload it to your github repo and link it here.
