### ISSUE TITLE
How to add Data, how do add data pre-6.3.2020

### ISSUE THREAD

**Issue by SchmidL** [daenuprobst/covid19-cases-switzerland#20]
Hi,

How can I contribute with additional data esp. historical data before the 6. march? 
Made a small search for Basel-Stadt, and found the history of their cases back to the 27. February when the first case in BS was published

**Comment by zdavatz** [comment]
Put the data into a file and publish your file on github.com. Then link your file to this issue. Use this format: https://github.com/openZH/covid_19/blob/master/COVID19_Fallzahlen_Kanton_BS_total.csv

**Comment by zdavatz** [comment]
Actually you can even send them a pull request.

**Comment by zdavatz** [comment]
https://github.com/openZH/covid_19/ they are now focusing on collecting all the data of Switzerland.

**Comment by SchmidL** [comment]
ok!
