### ISSUE TITLE
covid_19_cases_switzerland_standard_format.csv

### ISSUE THREAD

**Issue by cybermax** [daenuprobst/covid19-cases-switzerland#24]
Columns "total_currently_positive_cases" and "deaths" have identical values. Can you please double-check? Thx!

**Comment by zdavatz** [comment]
thank for reporting @cybermax

**Comment by daenuprobst** [comment]
Thanks for the hint on twitter @zdavatz .

It is fixed.

**Comment by zdavatz** [comment]
thank you too @daenuprobst - great work.
