### ISSUE TITLE
Todesfälle; entweder kumulativ oder täglich

### ISSUE THREAD

**Issue by zdavatz** [daenuprobst/covid19-cases-switzerland#25]
Kannst du die Todesfälle entweder kumulativ machen oder täglich (an dem Tag). Zur Zeit ist es eine Mischung und das ist verwirrend.

Wenn Todesfälle an einem Tag von einem Kanton nicht kommuniziert werden, dann einfach die Zahl des Vortages verwenden.

https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_fatalities_switzerland.csv

**Comment by daenuprobst** [comment]
Das ist kumulativ, habe aber keine Daten um alle Lücken zu füllen.  E.g. Zürich zwischen 1 und 3, da weiss ich nicht welche Nummer wo plazieren.

**Comment by zdavatz** [comment]
Kannst Du weiterfahren mit den Daten die Du hast, auch wenn Du nicht alle hast. Fahre einfach weiter mit der letzten Nummer die Du zuverlässig hattest. Geht das? Wenn keiner stirbt, bleibt es bei einem Toten.

**Comment by netzwerg** [comment]
Im Moment ist es sehr wichtig, nicht den falschen Eindruck zu erwecken, dass die Zahlen runter gehen (#42)

**Comment by zdavatz** [comment]
@netzwerg ja, das sehe ich auch so. Das Reporting via dem Faxformular vom BAG (neu auch Email) führt zu einem sehr `verzogenen` Reporting. HIN.ch ist jetzt aber darn die Fälle wie einem editierbaren Formular in einer DB abzulegen. Siehe auch https://twitter.com/zdavatz/status/1242433114565160962?s=20
