### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by pascalenderli** [daenuprobst/covid19-cases-switzerland#30]

**Comment by purzlbaum** [comment]
I think there is data for 18th march: https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_ZH_total.csv

**Comment by purzlbaum** [comment]
And there is a pull request already (which has merge conflicts currently): https://github.com/daenuprobst/covid19-cases-switzerland/pull/22
