### ISSUE TITLE
Error in title of world overview

### ISSUE THREAD

**Issue by GieziJo** [daenuprobst/covid19-cases-switzerland#35]
The title for this graph is wrong:
![image](https://user-images.githubusercontent.com/4385118/77395658-5e278800-6da2-11ea-928d-737f596f070c.png)
These are the total number of cases, not the prevalence per 10'000 people.

Also would it be possible to add switzerland in this graph and give the possibility to plot it in log in y?

P.S
Thanks for your work :)

**Comment by Drewsmits** [comment]
I think this was fixed. There is now a graph for "Total Cases for Switzerland" and a "Prevalence per 10,000 Inhabitants." Both appear to now show the correct data.

**Comment by GieziJo** [comment]
Yes it has been fixed 👍
