### ISSUE TITLE
Prevalence or cumulative incidence?

### ISSUE THREAD

**Issue by ghost** [daenuprobst/covid19-cases-switzerland#44]
Hello

Thank you for your work, which is very important. But I have one doubt:

You have a plot with the title "Prevalence per 10,000 Inhabitants". I'm not sure if you really mean "prevalence". Prevalance would be the total of the (infected persons at time)/population. Right now this is very similar to the cumulative incidence since not to many persons have recovered or died yet. I believe you actually report the cumulative incidence, which is the (cumulative case number at time)/(population at the beginning).

To be more clear why I believe this:
Italy had today 69176 confirmed cases (Johns Hopkins, 25.3).

Cumulative incidence per 10000: 69176/60262701*10000=11.48

At this time 8326 have recovered and 6820 have died.

The prevalence would therefore be around: 8.97.

You report for today: 11.44.

See here for a good introduction into the topic:

https://www.cdc.gov/csels/dsepd/ss1978/lesson3/section2.html

**Comment by philsinn** [comment]
No reply? I think the difference is quite important and your site is taken seriously by public health authorities.
