### ISSUE TITLE
Social distancing

### ISSUE THREAD

**Issue by fmgryerson** [daenuprobst/covid19-cases-switzerland#50]
Great site - thanks. It might be interesting to show some impact of social distancing. For example a projection of the number of days for the number of infections to double. I think the formula is simply ln(2)/ln(1+daily growth rate). 

Just a thought.

Thx

**Comment by zdavatz** [comment]
For that I think we need an App, so anybody who wants to share his location can share it.

**Comment by fmgryerson** [comment]
True. Sorry, I was thinking about something much simpler. The data implies that the total number of infections was doubling every two days or so early on. The last few days suggest that number is getting closer to 9 days. I appreciate it's dangerous to extrapolate but one conclusion is that social distancing is having a positive impact. A more robust regression model would allow the expression of confidence in any estimate but the simple formula at least is easy to chart daily.
