### ISSUE TITLE
Feature Request: moving average trend line of new cases

### ISSUE THREAD

**Issue by resmo** [daenuprobst/covid19-cases-switzerland#53]
There is currently a stat about new cases per Canton. In my opinion, a moving average trend line of total new cases per day would be very interesting. 

With the current situation of the lockdown the assumption is, a trend line would show the results of these regulations. I median value is suggested because the data publishing is not coordinated and may vary much.

To show an example: https://plotly.com/~tongmanhok/4/simple-moving-averages/#plot

**Comment by matjung** [comment]
And what will be the political impact if the trend goes up / down ?
