### ISSUE TITLE
Worthless map on the site

### ISSUE THREAD

**Issue by g-st-ch** [daenuprobst/covid19-cases-switzerland#72]
On your site https://www.corona-data.ch/ the first graphic is not only worthless but incorrect at my point of view. BS has nearly the same color as BE, but BS has a population of 200k and BE of more than 1000k. So BS should be much more red than BE. Please include the population numbers of the cantons in the calculation of coloring in your map. Thank you for your great work.

**Comment by davidperrenoud** [comment]
You can now choose "Cumulative Prevalence (per 10,000)" to get data normalised by the canton population.

**Comment by g-st-ch** [comment]
Great expansion of this graph. Thank you very much, David!

**Comment by davidperrenoud** [comment]
You want to thank @daenuprobst. ;)

Could you close the issue?
